spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vms?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  #上传文件配置
  servlet:
    multipart:
      maxFileSize: 100MB
      maxRequestSize: 200MB

# Server settings (ServerProperties)
server:
  port: 8888
  servlet:
    context-path: /vms

log:
  level: INFO
  path: D:/logs/vehicle-manage-system

cors:
  #  allowedOrigins: 'http://192.168.5.114:8088'
  allowedOrigins: 'http://192.168.2.182:8088'